In [6]:
import numpy as np


scores = np.array([
    [85, 92, 78],  # 学生A
    [90, 88, 95],  # 学生B
    [76, 85, 82],  # 学生C
    [92, 79, 88],  # 学生D
    [88, 95, 90]   # 学生E
])

students = ['学生A', '学生B', '学生C', '学生D', '学生E']
subjects = ['语文', '数学', '英语']


extra = np.array([2, 3, 1, 4, 2]).reshape(-1, 1)  # 转为列向量，方便广播
scores_with_extra = scores + extra

In [7]:

total_scores = scores_with_extra.sum(axis=1)


for i, student in enumerate(students):
    print(f"{student}：{total_scores[i]}分")

学生A：261分
学生B：282分
学生C：246分
学生D：271分
学生E：279分


In [8]:

rank_idx = np.argsort(total_scores)[::-1]


sorted_students = [students[i] for i in rank_idx]
sorted_totals = total_scores[rank_idx]


print("\n按总分从高到低排序：")
for student, total in zip(sorted_students, sorted_totals):
    print(f"{student}：{total}分")


按总分从高到低排序：
学生B：282分
学生E：279分
学生D：271分
学生A：261分
学生C：246分


In [9]:

scores_transposed = scores_with_extra.T

print("\n转置后的数组（行：科目，列：学生A-E）：")
print(scores_transposed)


转置后的数组（行：科目，列：学生A-E）：
[[87 93 77 96 90]
 [94 91 86 83 97]
 [80 98 83 92 92]]


In [10]:

chinese_scores, other_scores = np.hsplit(scores_with_extra, [1])

print("\n语文成绩：")
print(chinese_scores)
print("\n其他科目成绩（数学、英语）：")
print(other_scores)


语文成绩：
[[87]
 [93]
 [77]
 [96]
 [90]]

其他科目成绩（数学、英语）：
[[94 80]
 [91 98]
 [86 83]
 [83 92]
 [97 92]]
