In [ ]:
import numpy as np


rows = np.arange(8).reshape(8, 1)  
cols = np.arange(8)


chessboard = (rows + cols) % 2


print("8×8 国际象棋棋盘矩阵（1=黑格，0=白格）：")
print(chessboard)

8×8 国际象棋棋盘矩阵（1=黑格，0=白格）：
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
