In [ ]:
import numpy as np


q1_sales = np.array([120, 95, 150])  
q2_sales = np.array([135, 110, 165]) 


vertical_report = np.vstack([q1_sales, q2_sales])

horizontal_report = np.hstack([q1_sales, q2_sales])


annual_total = vertical_report.sum(axis=0)

print("=== 季度销售数据 ===")
print("第1季度销售额：", q1_sales)
print("第2季度销售额：", q2_sales)

print("\n=== 垂直合并报表（行：季度，列：产品）===")
print(vertical_report)

print("\n=== 水平合并报表（前3列：Q1，后3列：Q2）===")
print(horizontal_report)

print("\n=== 各产品全年总销售额 ===")
products = ['产品A', '产品B', '产品C']
for product, total in zip(products, annual_total):
    print(f"{product}：{total}")

=== 季度销售数据 ===
第1季度销售额： [120  95 150]
第2季度销售额： [135 110 165]

=== 垂直合并报表（行：季度，列：产品）===
[[120  95 150]
 [135 110 165]]

=== 水平合并报表（前3列：Q1，后3列：Q2）===
[120  95 150 135 110 165]

=== 各产品全年总销售额 ===
产品A：255
产品B：205
产品C：315
